#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause

"""
simple wrapper around graffle2svg for use as a viewer

use:
graffle2svgview FILENAME
"""

if __name__ == "__main__":
	from optparse import OptionParser
	usage = '%prog FILE'
	parser = OptionParser(usage=usage)
	(options, args) = parser.parse_args()
	if len(args) > 2:
		parser.error("Too many arguments")
	elif len(args) < 1:
		parser.error("Filename missed")

	import subprocess, sys
	subprocess.call(('graffle2svg', "-d", sys.argv[1]))
